### PR TITLE
Grammatical & punctuational fixes in the readme.

### PR DESCRIPTION
**Pull request by EwanGreen4**
Additionally, fixed a 404 from the old liboobs GitHub repository that has since been removed.

### CODE REVIEW

**Comment by tsujan** [comment]
Thanks!

I think limiting the line width to 90 characters was intentional, although I'm not sure why.

**Comment by EwanGreen4** [comment]
Assuming it's 90 characters for markdown display and not the plaintext, the latest commit should be up to specification.

**Comment by tsujan** [comment]
> Assuming it's 90 characters for markdown display and not the plaintext, the latest commit should be up to specification

But now, it has lines with more than 100 characters. Sorry, I should have been more specific: whitespace is also taken into account. In text editing, we have the concepts of "position" and "length". You might want to use a text editor that shows the cursor position (FeatherPad does when its status-bar is activated).

That being said, I don't know from where this restriction comes or how important it is. Maybe, another LXQt member could shed some light on it.

**Comment by EwanGreen4** [comment]
I see. I determined my line lengths by the displayed result: accounting for embedded links within the markdown text, none of the lines should have contained over 90 characters. I used KWrite to do this, so I was aware of the actual plaintext line lengths (every line devoid of links should be less than 90 characters). It was just a matter of enforcing the plaintext 90 character limit on the lines with links as well, if I'm not mistaken. One thing that confuses me is that the bottom portion of the document (containing the image embed for the translation info) doesn't seem to follow this 90 character or less rule. Thoughts?

**Comment by tsujan** [comment]
> One thing that confuses me is that the bottom portion of the document (containing the image embed for the translation info) doesn't seem to follow this 90 character or less rule. Thoughts?

Yes, I noticed it; it was adder later. The "rule" -- if any -- may be only for the ease of use with terminal-based editors and not strict. For now, let's stick with 90 for the doc body and ignore the rest.

Anyway, your patch seems neat to me.

**Comment by EwanGreen4** [comment]
> Yes, I noticed it; it was added later. The "rule" -- if any -- may be only for the ease of use with terminal-based editors and not strict.

Ah, that would make sense. On top of that, the image embed + the URL exceed 90 characters anyway, so it might not have been a mistake -- just a requirement to get the graph to embed in the first place.

> Anyway, your patch seems neat to me.

Thanks!

**Review by tsujan — APPROVED** [review]
GTM

**Comment by tsujan** [comment]
It means "Good to merge": an official approval.

**Pull request merged**
