### PR TITLE
lxqt-admin on NetBSD

### PR DESCRIPTION
**Pull request by voidpin**
Avoid non portable == shell test usage and allow lxqt-admin-user to build and install on NetBSD.
Only lxqt-admin-time is dependent on systemd. Keep system warning about it but allow to install package.
@palinek 
Hope this is fine now

### CODE REVIEW

**Comment by palinek** [comment]
> Would this make sense?

Did you even make any changes to the commits? Seems very same as in #196

**Comment by voidpin** [comment]
Yes, CMakeLists.txt should read,
```
 36 if(${CMAKE_SYSTEM_NAME} MATCHES "OpenBSD" OR ${CMAKE_SYSTEM_NAME} MATCHES "NetBSD")
 37     message(WARNING "${CMAKE_SYSTEM_NAME} is not supported by lxqt-admin-time")
 38     add_subdirectory(lxqt-admin-user)
 39 else()
 40     add_subdirectory(lxqt-admin-user)
 41     add_subdirectory(lxqt-admin-time)
 42 endif()                                                                                                                                           
```
i.e. keep the WARNING about `lxqt-admin-time` but allowing the package to build. Build verified on NetBSD-9.0_RC2

**Comment by voidpin** [comment]
@palinek 
Is it clear or should I provide anything else?

**Comment by palinek** [comment]
> Is it clear or should I provide anything else?

The final diff/patch is OK, but I'm not a fan of splitting one change into multiple commits ... I believe the cf7855b and 8842dd6 should be merged as 1 commit. Therefore I've asked you to squash (https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_squashing) them in previous PR.

**Comment by voidpin** [comment]
Apparently I can't squash the commits.
Let me close this, delete my fork, re-fork a create a new pull request with both commits in one.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Pull request closed without merging**
