### PR TITLE
lxqt-admin-time for FreeBSD

### PR DESCRIPTION
**Pull request by jsm222**
Another attempt. Tested on both Linux and FreeBSD.
The setters on FreeBSD caches arguments for a lxqt-admin-time-helper script.
The getters does not require root.
Replaces #46

### CODE REVIEW

**Comment by PCMan** [comment]
@jsm222 Awesome! Thanks for the hard work. I don't have FreeBSD to test it but I will do the code review.

**Comment by agaida** [comment]
@jsm222 - that means that https://github.com/lxqt/lxqt-admin/pull/46 is obsolete?

**Comment by jsm222** [comment]
@agaida  Yes it replaces my previous #46.
I'll squash the commits if accepted. The update just takes into account that it takes the user some time to enter the password in the polkit agent. The time that passes from OK in admin-time gui to helper-script  is being executed is calculated. This is only for FreeBSD I dont know how dbus handles this..

**Comment by agaida** [comment]
@jsm222 - would you be so kind and solve the merge conflics?

**Comment by yan12125** [comment]
Can't build with git-master of lxqt-build-tools:
```
[ 92%] Building CXX object lxqt-admin-time/CMakeFiles/lxqt-admin-time.dir/fbsdtimedatectl.cpp.o
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp: In member function ‘virtual QString FBSDTimeDateCtl::timeZone() const’:
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:47:36: error: ‘QString::QString(const char*)’ is private within this context
     QFile tzFile("/var/db/zoneinfo");
                                    ^
In file included from /usr/include/qt/QtCore/QString:1,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.h:30,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:28:
/usr/include/qt/QtCore/qstring.h:829:5: note: declared private here
     QString(const char *ch);
     ^~~~~~~
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:48:66: error: ‘QString::QString(const char*)’ is private within this context
          if (!tzFile.open(QFile::ReadOnly | QFile::Text)) return "Unknown";
                                                                  ^~~~~~~~~
In file included from /usr/include/qt/QtCore/QString:1,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.h:30,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:28:
/usr/include/qt/QtCore/qstring.h:829:5: note: declared private here
     QString(const char *ch);
     ^~~~~~~
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp: In member function ‘virtual bool FBSDTimeDateCtl::setTimeZone(QString, QString&)’:
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:57:20: error: ‘QString::QString(const char*)’ is private within this context
     mHelperArgs << "-t" << timeZone;
                    ^~~~
In file included from /usr/include/qt/QtCore/QString:1,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.h:30,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:28:
/usr/include/qt/QtCore/qstring.h:829:5: note: declared private here
     QString(const char *ch);
     ^~~~~~~
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:55:62: warning: unused parameter ‘errorMessage’ [-Wunused-parameter]
 bool FBSDTimeDateCtl::setTimeZone(QString timeZone, QString& errorMessage)
                                                     ~~~~~~~~~^~~~~~~~~~~~
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp: In member function ‘virtual bool FBSDTimeDateCtl::setDateTime(QDateTime, QString&)’:
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:64:20: error: ‘QString::QString(const char*)’ is private within this context
     mHelperArgs << "-d" << QString::number(epochsec);
                    ^~~~
In file included from /usr/include/qt/QtCore/QString:1,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.h:30,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:28:
/usr/include/qt/QtCore/qstring.h:829:5: note: declared private here
     QString(const char *ch);
     ^~~~~~~
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:61:64: warning: unused parameter ‘errorMessage’ [-Wunused-parameter]
 bool FBSDTimeDateCtl::setDateTime(QDateTime dateTime, QString& errorMessage)
                                                       ~~~~~~~~~^~~~~~~~~~~~
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp: In member function ‘virtual bool FBSDTimeDateCtl::useNtp() const’:
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:76:47: error: ‘QString::QString(const QByteArray&)’ is private within this context
     QString t = process.readAllStandardOutput();
                                               ^
In file included from /usr/include/qt/QtCore/QString:1,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.h:30,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:28:
/usr/include/qt/QtCore/qstring.h:830:5: note: declared private here
     QString(const QByteArray &a);
     ^~~~~~~
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:77:33: error: ‘QString::QString(const char*)’ is private within this context
     QStringList o = t.split("\n");
                                 ^
In file included from /usr/include/qt/QtCore/QString:1,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.h:30,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:28:
/usr/include/qt/QtCore/qstring.h:829:5: note: declared private here
     QString(const char *ch);
     ^~~~~~~
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:81:35: error: ‘QString::QString(const char*)’ is private within this context
         if(!current.startsWith("#") && current.contains(QString("ntpd_enable"),Qt::CaseInsensitive) && current.contains(QString("yes"),Qt::CaseInsensitive)) {
                                   ^
In file included from /usr/include/qt/QtCore/QString:1,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.h:30,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:28:
/usr/include/qt/QtCore/qstring.h:829:5: note: declared private here
     QString(const char *ch);
     ^~~~~~~
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:81:78: error: ‘QString::QString(const char*)’ is private within this context
         if(!current.startsWith("#") && current.contains(QString("ntpd_enable"),Qt::CaseInsensitive) && current.contains(QString("yes"),Qt::CaseInsensitive)) {
                                                                              ^
In file included from /usr/include/qt/QtCore/QString:1,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.h:30,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:28:
/usr/include/qt/QtCore/qstring.h:829:5: note: declared private here
     QString(const char *ch);
     ^~~~~~~
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:81:134: error: ‘QString::QString(const char*)’ is private within this context
         if(!current.startsWith("#") && current.contains(QString("ntpd_enable"),Qt::CaseInsensitive) && current.contains(QString("yes"),Qt::CaseInsensitive)) {
                                                                                                                                      ^
In file included from /usr/include/qt/QtCore/QString:1,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.h:30,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:28:
/usr/include/qt/QtCore/qstring.h:829:5: note: declared private here
     QString(const char *ch);
     ^~~~~~~
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp: In member function ‘virtual bool FBSDTimeDateCtl::setUseNtp(bool, QString&)’:
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:90:20: error: ‘QString::QString(const char*)’ is private within this context
     mHelperArgs << "-n" << (value ? "true" : "false");
                    ^~~~
In file included from /usr/include/qt/QtCore/QString:1,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.h:30,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:28:
/usr/include/qt/QtCore/qstring.h:829:5: note: declared private here
     QString(const char *ch);
     ^~~~~~~
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:90:53: error: ‘QString::QString(const char*)’ is private within this context
     mHelperArgs << "-n" << (value ? "true" : "false");
                                                     ^
In file included from /usr/include/qt/QtCore/QString:1,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.h:30,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:28:
/usr/include/qt/QtCore/qstring.h:829:5: note: declared private here
     QString(const char *ch);
     ^~~~~~~
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:88:54: warning: unused parameter ‘errorMessage’ [-Wunused-parameter]
 bool FBSDTimeDateCtl::setUseNtp(bool value, QString& errorMessage)
                                             ~~~~~~~~~^~~~~~~~~~~~
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp: In member function ‘virtual bool FBSDTimeDateCtl::localRtc() const’:
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:96:44: error: ‘QString::QString(const char*)’ is private within this context
     return QFileInfo("/etc/wall_cmos_clock").exists();
                                            ^
In file included from /usr/include/qt/QtCore/QString:1,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.h:30,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:28:
/usr/include/qt/QtCore/qstring.h:829:5: note: declared private here
     QString(const char *ch);
     ^~~~~~~
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp: In member function ‘virtual bool FBSDTimeDateCtl::setLocalRtc(bool, QString&)’:
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:101:20: error: ‘QString::QString(const char*)’ is private within this context
     mHelperArgs << "-l" << (value ? "true" : "false");
                    ^~~~
In file included from /usr/include/qt/QtCore/QString:1,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.h:30,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:28:
/usr/include/qt/QtCore/qstring.h:829:5: note: declared private here
     QString(const char *ch);
     ^~~~~~~
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:101:53: error: ‘QString::QString(const char*)’ is private within this context
     mHelperArgs << "-l" << (value ? "true" : "false");
                                                     ^
In file included from /usr/include/qt/QtCore/QString:1,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.h:30,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:28:
/usr/include/qt/QtCore/qstring.h:829:5: note: declared private here
     QString(const char *ch);
     ^~~~~~~
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:99:56: warning: unused parameter ‘errorMessage’ [-Wunused-parameter]
 bool FBSDTimeDateCtl::setLocalRtc(bool value, QString& errorMessage)
                                               ~~~~~~~~~^~~~~~~~~~~~
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp: In member function ‘bool FBSDTimeDateCtl::pkexec()’:
/build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:122:126: error: ‘QString::QString(const char*)’ is private within this context
             , QObject::tr("<strong>Action (%1) failed:</strong><br/><pre>%2</pre>").arg(args[0]).arg(pkexec_error.constData())};
                                                                                                                              ^
In file included from /usr/include/qt/QtCore/QString:1,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.h:30,
                 from /build/lxqt-admin-git/src/lxqt-admin/lxqt-admin-time/fbsdtimedatectl.cpp:28:
/usr/include/qt/QtCore/qstring.h:829:5: note: declared private here
     QString(const char *ch);
     ^~~~~~~
```

**Comment by agaida** [comment]
and i guess i should revert that.

**Comment by agaida** [comment]
Reverted - Note to myself: Alf, you should be able to rebase things most of the time - if not something tends to be horrible wrong! (Guess i have learned that now ...)

**Comment by yan12125** [comment]
Maybe we should setup CI builds, too

**Comment by yan12125** [comment]
Anyway, @jsm222, please open a new pull request after fixing QString issues.

**Pull request merged**
