### PR TITLE
Let admin-user build on NBSD and avoid "=="

### PR DESCRIPTION
**Pull request by voidpin**
@palinek 
Sorry for taking your time. Hope this is as you want it now.
Please let me know if you need anything else.

### CODE REVIEW

**Comment by voidpin** [comment]
Sorry to ask but, is there something stopping the merge?
I would like to finish the LXQt port to NetBSD next week.

**Comment by voidpin** [comment]
The port is complete.
Still some edges to iron out but, mostly fine.

2020-02-16-192755-1366x768-scrot

The main issue right now is with the initial login. After choosing the window manager only a black screen is seen. The panel is there but, its black on black background. Right click and changing the color of the panel or, setting the wallpaper, makes it much easier. Is there something I can do while packaging to force either the color of the panel or the wallpaper?
Thanks for any hints.

**Comment by palinek** [comment]
Landed in 7adcc9abfe95112e6352ad63e5748b8c80e1e29c & f613d1b8f637a32d511bc01bca53895f75628215

**Comment by palinek** [comment]
> Is there something I can do while packaging to force either the color of the panel or the wallpaper?

If you use the upstream's `/etc/xdg/autostart/lxqt-desktop.desktop` (`pcmanfm-qt --desktop --profile=lxqt`), then you can provide a decent wallpaper in one of the `XDG_CONFIG_DIRS`/pcmafm-qt/lxqt/settings.conf (in `[Desktop]` section) config files.

**Comment by voidpin** [comment]
Thank you I'll look into it.

**Pull request closed without merging**
